"""ZCL constants used by uzigbee.

Values are aligned with ESP Zigbee SDK headers used by firmware builds.
"""

try:
    from micropython import const
except ImportError:
    def const(x):
        return x


# Cluster IDs (selected, commonly used in HA and upcoming uzigbee phases).
CLUSTER_ID_BASIC = const(0x0000)
CLUSTER_ID_POWER_CONFIG = const(0x0001)
CLUSTER_ID_IDENTIFY = const(0x0003)
CLUSTER_ID_GROUPS = const(0x0004)
CLUSTER_ID_SCENES = const(0x0005)
CLUSTER_ID_ON_OFF = const(0x0006)
CLUSTER_ID_LEVEL_CONTROL = const(0x0008)
CLUSTER_ID_TIME = const(0x000A)
CLUSTER_ID_OTA_UPGRADE = const(0x0019)
CLUSTER_ID_DOOR_LOCK = const(0x0101)
CLUSTER_ID_WINDOW_COVERING = const(0x0102)
CLUSTER_ID_THERMOSTAT = const(0x0201)
CLUSTER_ID_THERMOSTAT_UI_CONFIG = const(0x0204)
CLUSTER_ID_COLOR_CONTROL = const(0x0300)
CLUSTER_ID_ILLUMINANCE_MEASUREMENT = const(0x0400)
CLUSTER_ID_TEMP_MEASUREMENT = const(0x0402)
CLUSTER_ID_PRESSURE_MEASUREMENT = const(0x0403)
CLUSTER_ID_FLOW_MEASUREMENT = const(0x0404)
CLUSTER_ID_REL_HUMIDITY_MEASUREMENT = const(0x0405)
CLUSTER_ID_OCCUPANCY_SENSING = const(0x0406)
CLUSTER_ID_IAS_ZONE = const(0x0500)
CLUSTER_ID_IAS_ACE = const(0x0501)
CLUSTER_ID_IAS_WD = const(0x0502)
CLUSTER_ID_METERING = const(0x0702)
CLUSTER_ID_ELECTRICAL_MEASUREMENT = const(0x0B04)
CLUSTER_ID_DIAGNOSTICS = const(0x0B05)

# Backward-compatible aliases (legacy names used in early tests/examples).
CLUSTER_BASIC = CLUSTER_ID_BASIC
CLUSTER_ON_OFF = CLUSTER_ID_ON_OFF


# Global attribute IDs.
ATTR_CLUSTER_REVISION = const(0xFFFD)
ATTR_REPORTING_STATUS = const(0xFFFE)


# Basic cluster attribute IDs.
ATTR_BASIC_ZCL_VERSION = const(0x0000)
ATTR_BASIC_APPLICATION_VERSION = const(0x0001)
ATTR_BASIC_STACK_VERSION = const(0x0002)
ATTR_BASIC_HW_VERSION = const(0x0003)
ATTR_BASIC_MANUFACTURER_NAME = const(0x0004)
ATTR_BASIC_MODEL_IDENTIFIER = const(0x0005)
ATTR_BASIC_DATE_CODE = const(0x0006)
ATTR_BASIC_POWER_SOURCE = const(0x0007)
ATTR_BASIC_GENERIC_DEVICE_CLASS = const(0x0008)
ATTR_BASIC_GENERIC_DEVICE_TYPE = const(0x0009)
ATTR_BASIC_PRODUCT_CODE = const(0x000A)
ATTR_BASIC_PRODUCT_URL = const(0x000B)
ATTR_BASIC_MANUFACTURER_VERSION_DETAILS = const(0x000C)
ATTR_BASIC_SERIAL_NUMBER = const(0x000D)
ATTR_BASIC_PRODUCT_LABEL = const(0x000E)
ATTR_BASIC_LOCATION_DESCRIPTION = const(0x0010)
ATTR_BASIC_PHYSICAL_ENVIRONMENT = const(0x0011)
ATTR_BASIC_DEVICE_ENABLED = const(0x0012)
ATTR_BASIC_ALARM_MASK = const(0x0013)
ATTR_BASIC_DISABLE_LOCAL_CONFIG = const(0x0014)
ATTR_BASIC_SW_BUILD_ID = const(0x4000)

# Backward-compatible aliases (legacy names).
ATTR_ZCL_VERSION = ATTR_BASIC_ZCL_VERSION
ATTR_APPLICATION_VERSION = ATTR_BASIC_APPLICATION_VERSION
ATTR_STACK_VERSION = ATTR_BASIC_STACK_VERSION
ATTR_HW_VERSION = ATTR_BASIC_HW_VERSION
ATTR_MANUFACTURER_NAME = ATTR_BASIC_MANUFACTURER_NAME
ATTR_MODEL_IDENTIFIER = ATTR_BASIC_MODEL_IDENTIFIER
ATTR_DATE_CODE = ATTR_BASIC_DATE_CODE
ATTR_POWER_SOURCE = ATTR_BASIC_POWER_SOURCE
ATTR_SW_BUILD_ID = ATTR_BASIC_SW_BUILD_ID


# On/Off cluster attribute IDs.
ATTR_ON_OFF_ON_OFF = const(0x0000)
ATTR_ON_OFF_GLOBAL_SCENE_CONTROL = const(0x4000)
ATTR_ON_OFF_ON_TIME = const(0x4001)
ATTR_ON_OFF_OFF_WAIT_TIME = const(0x4002)
ATTR_ON_OFF_START_UP_ON_OFF = const(0x4003)

# Backward-compatible alias (legacy name).
ATTR_ON_OFF = ATTR_ON_OFF_ON_OFF


# Level Control cluster attribute IDs.
ATTR_LEVEL_CONTROL_CURRENT_LEVEL = const(0x0000)
ATTR_LEVEL_CONTROL_REMAINING_TIME = const(0x0001)
ATTR_LEVEL_CONTROL_MIN_LEVEL = const(0x0002)
ATTR_LEVEL_CONTROL_MAX_LEVEL = const(0x0003)
ATTR_LEVEL_CONTROL_OPTIONS = const(0x000F)
ATTR_LEVEL_CONTROL_ON_OFF_TRANSITION_TIME = const(0x0010)
ATTR_LEVEL_CONTROL_ON_LEVEL = const(0x0011)
ATTR_LEVEL_CONTROL_ON_TRANSITION_TIME = const(0x0012)
ATTR_LEVEL_CONTROL_OFF_TRANSITION_TIME = const(0x0013)
ATTR_LEVEL_CONTROL_DEFAULT_MOVE_RATE = const(0x0014)
ATTR_LEVEL_CONTROL_START_UP_CURRENT_LEVEL = const(0x4000)


# Color Control cluster attribute IDs.
ATTR_COLOR_CONTROL_CURRENT_HUE = const(0x0000)
ATTR_COLOR_CONTROL_CURRENT_SATURATION = const(0x0001)
ATTR_COLOR_CONTROL_REMAINING_TIME = const(0x0002)
ATTR_COLOR_CONTROL_CURRENT_X = const(0x0003)
ATTR_COLOR_CONTROL_CURRENT_Y = const(0x0004)
ATTR_COLOR_CONTROL_COLOR_TEMPERATURE = const(0x0007)
ATTR_COLOR_CONTROL_COLOR_MODE = const(0x0008)
ATTR_COLOR_CONTROL_OPTIONS = const(0x000F)
ATTR_COLOR_CONTROL_ENHANCED_CURRENT_HUE = const(0x4000)
ATTR_COLOR_CONTROL_ENHANCED_COLOR_MODE = const(0x4001)
ATTR_COLOR_CONTROL_COLOR_LOOP_ACTIVE = const(0x4002)
ATTR_COLOR_CONTROL_COLOR_LOOP_DIRECTION = const(0x4003)
ATTR_COLOR_CONTROL_COLOR_LOOP_TIME = const(0x4004)
ATTR_COLOR_CONTROL_COLOR_CAPABILITIES = const(0x400A)
ATTR_COLOR_CONTROL_COLOR_TEMP_PHYSICAL_MIN_MIREDS = const(0x400B)
ATTR_COLOR_CONTROL_COLOR_TEMP_PHYSICAL_MAX_MIREDS = const(0x400C)
ATTR_COLOR_CONTROL_START_UP_COLOR_TEMPERATURE_MIREDS = const(0x4010)


# Sensor cluster attribute IDs.
ATTR_TEMP_MEASUREMENT_VALUE = const(0x0000)
ATTR_TEMP_MEASUREMENT_MIN_VALUE = const(0x0001)
ATTR_TEMP_MEASUREMENT_MAX_VALUE = const(0x0002)
ATTR_TEMP_MEASUREMENT_TOLERANCE = const(0x0003)

ATTR_REL_HUMIDITY_MEASUREMENT_VALUE = const(0x0000)
ATTR_REL_HUMIDITY_MEASUREMENT_MIN_VALUE = const(0x0001)
ATTR_REL_HUMIDITY_MEASUREMENT_MAX_VALUE = const(0x0002)

ATTR_PRESSURE_MEASUREMENT_VALUE = const(0x0000)
ATTR_PRESSURE_MEASUREMENT_MIN_VALUE = const(0x0001)
ATTR_PRESSURE_MEASUREMENT_MAX_VALUE = const(0x0002)
ATTR_PRESSURE_MEASUREMENT_TOLERANCE = const(0x0003)
ATTR_PRESSURE_MEASUREMENT_SCALED_VALUE = const(0x0010)
ATTR_PRESSURE_MEASUREMENT_SCALE = const(0x0014)

ATTR_OCCUPANCY_SENSING_OCCUPANCY = const(0x0000)
ATTR_OCCUPANCY_SENSING_OCCUPANCY_SENSOR_TYPE = const(0x0001)
ATTR_OCCUPANCY_SENSING_OCCUPANCY_SENSOR_TYPE_BITMAP = const(0x0002)

ATTR_IAS_ZONE_STATE = const(0x0000)
ATTR_IAS_ZONE_TYPE = const(0x0001)
ATTR_IAS_ZONE_STATUS = const(0x0002)
ATTR_IAS_ZONE_IAS_CIE_ADDRESS = const(0x0010)
ATTR_IAS_ZONE_ID = const(0x0011)


# ZCL data types (ESP_ZB_ZCL_ATTR_TYPE_*).
DATA_TYPE_NULL = const(0x00)
DATA_TYPE_8BIT = const(0x08)
DATA_TYPE_16BIT = const(0x09)
DATA_TYPE_24BIT = const(0x0A)
DATA_TYPE_32BIT = const(0x0B)
DATA_TYPE_40BIT = const(0x0C)
DATA_TYPE_48BIT = const(0x0D)
DATA_TYPE_56BIT = const(0x0E)
DATA_TYPE_64BIT = const(0x0F)
DATA_TYPE_BOOL = const(0x10)
DATA_TYPE_8BITMAP = const(0x18)
DATA_TYPE_16BITMAP = const(0x19)
DATA_TYPE_24BITMAP = const(0x1A)
DATA_TYPE_32BITMAP = const(0x1B)
DATA_TYPE_40BITMAP = const(0x1C)
DATA_TYPE_48BITMAP = const(0x1D)
DATA_TYPE_56BITMAP = const(0x1E)
DATA_TYPE_64BITMAP = const(0x1F)
DATA_TYPE_U8 = const(0x20)
DATA_TYPE_U16 = const(0x21)
DATA_TYPE_U24 = const(0x22)
DATA_TYPE_U32 = const(0x23)
DATA_TYPE_U40 = const(0x24)
DATA_TYPE_U48 = const(0x25)
DATA_TYPE_U56 = const(0x26)
DATA_TYPE_U64 = const(0x27)
DATA_TYPE_S8 = const(0x28)
DATA_TYPE_S16 = const(0x29)
DATA_TYPE_S24 = const(0x2A)
DATA_TYPE_S32 = const(0x2B)
DATA_TYPE_S40 = const(0x2C)
DATA_TYPE_S48 = const(0x2D)
DATA_TYPE_S56 = const(0x2E)
DATA_TYPE_S64 = const(0x2F)
DATA_TYPE_8BIT_ENUM = const(0x30)
DATA_TYPE_16BIT_ENUM = const(0x31)
DATA_TYPE_SEMI = const(0x38)
DATA_TYPE_SINGLE = const(0x39)
DATA_TYPE_DOUBLE = const(0x3A)
DATA_TYPE_OCTET_STRING = const(0x41)
DATA_TYPE_CHAR_STRING = const(0x42)
DATA_TYPE_LONG_OCTET_STRING = const(0x43)
DATA_TYPE_LONG_CHAR_STRING = const(0x44)
DATA_TYPE_ARRAY = const(0x48)
DATA_TYPE_16BIT_ARRAY = const(0x49)
DATA_TYPE_32BIT_ARRAY = const(0x4A)
DATA_TYPE_STRUCTURE = const(0x4C)
DATA_TYPE_SET = const(0x50)
DATA_TYPE_BAG = const(0x51)
DATA_TYPE_TIME_OF_DAY = const(0xE0)
DATA_TYPE_DATE = const(0xE1)
DATA_TYPE_UTC_TIME = const(0xE2)
DATA_TYPE_CLUSTER_ID = const(0xE8)
DATA_TYPE_ATTRIBUTE_ID = const(0xE9)
DATA_TYPE_BACNET_OID = const(0xEA)
DATA_TYPE_IEEE_ADDR = const(0xF0)
DATA_TYPE_128_BIT_KEY = const(0xF1)
DATA_TYPE_INVALID = const(0xFF)


_CLUSTER_NAMES = {
    CLUSTER_ID_BASIC: "basic",
    CLUSTER_ID_IDENTIFY: "identify",
    CLUSTER_ID_GROUPS: "groups",
    CLUSTER_ID_SCENES: "scenes",
    CLUSTER_ID_ON_OFF: "on_off",
    CLUSTER_ID_LEVEL_CONTROL: "level_control",
    CLUSTER_ID_COLOR_CONTROL: "color_control",
    CLUSTER_ID_TEMP_MEASUREMENT: "temperature_measurement",
    CLUSTER_ID_PRESSURE_MEASUREMENT: "pressure_measurement",
    CLUSTER_ID_REL_HUMIDITY_MEASUREMENT: "relative_humidity_measurement",
    CLUSTER_ID_OCCUPANCY_SENSING: "occupancy_sensing",
    CLUSTER_ID_IAS_ZONE: "ias_zone",
    CLUSTER_ID_THERMOSTAT: "thermostat",
    CLUSTER_ID_WINDOW_COVERING: "window_covering",
    CLUSTER_ID_DOOR_LOCK: "door_lock",
    CLUSTER_ID_METERING: "metering",
    CLUSTER_ID_ELECTRICAL_MEASUREMENT: "electrical_measurement",
}

_DATA_TYPE_NAMES = {
    DATA_TYPE_NULL: "null",
    DATA_TYPE_BOOL: "bool",
    DATA_TYPE_U8: "u8",
    DATA_TYPE_U16: "u16",
    DATA_TYPE_U32: "u32",
    DATA_TYPE_S8: "s8",
    DATA_TYPE_S16: "s16",
    DATA_TYPE_S32: "s32",
    DATA_TYPE_8BIT_ENUM: "enum8",
    DATA_TYPE_16BIT_ENUM: "enum16",
    DATA_TYPE_OCTET_STRING: "octet_string",
    DATA_TYPE_CHAR_STRING: "char_string",
    DATA_TYPE_LONG_OCTET_STRING: "long_octet_string",
    DATA_TYPE_LONG_CHAR_STRING: "long_char_string",
    DATA_TYPE_TIME_OF_DAY: "time_of_day",
    DATA_TYPE_DATE: "date",
    DATA_TYPE_UTC_TIME: "utc_time",
    DATA_TYPE_CLUSTER_ID: "cluster_id",
    DATA_TYPE_ATTRIBUTE_ID: "attribute_id",
    DATA_TYPE_IEEE_ADDR: "ieee_addr",
    DATA_TYPE_128_BIT_KEY: "key128",
}

_FIXED_DATA_TYPE_SIZES = {
    DATA_TYPE_NULL: 0,
    DATA_TYPE_8BIT: 1,
    DATA_TYPE_16BIT: 2,
    DATA_TYPE_24BIT: 3,
    DATA_TYPE_32BIT: 4,
    DATA_TYPE_40BIT: 5,
    DATA_TYPE_48BIT: 6,
    DATA_TYPE_56BIT: 7,
    DATA_TYPE_64BIT: 8,
    DATA_TYPE_BOOL: 1,
    DATA_TYPE_8BITMAP: 1,
    DATA_TYPE_16BITMAP: 2,
    DATA_TYPE_24BITMAP: 3,
    DATA_TYPE_32BITMAP: 4,
    DATA_TYPE_U8: 1,
    DATA_TYPE_U16: 2,
    DATA_TYPE_U24: 3,
    DATA_TYPE_U32: 4,
    DATA_TYPE_U40: 5,
    DATA_TYPE_U48: 6,
    DATA_TYPE_U56: 7,
    DATA_TYPE_U64: 8,
    DATA_TYPE_S8: 1,
    DATA_TYPE_S16: 2,
    DATA_TYPE_S24: 3,
    DATA_TYPE_S32: 4,
    DATA_TYPE_S40: 5,
    DATA_TYPE_S48: 6,
    DATA_TYPE_S56: 7,
    DATA_TYPE_S64: 8,
    DATA_TYPE_8BIT_ENUM: 1,
    DATA_TYPE_16BIT_ENUM: 2,
    DATA_TYPE_SINGLE: 4,
    DATA_TYPE_DOUBLE: 8,
    DATA_TYPE_TIME_OF_DAY: 4,
    DATA_TYPE_DATE: 4,
    DATA_TYPE_UTC_TIME: 4,
    DATA_TYPE_CLUSTER_ID: 2,
    DATA_TYPE_ATTRIBUTE_ID: 2,
    DATA_TYPE_BACNET_OID: 4,
    DATA_TYPE_IEEE_ADDR: 8,
    DATA_TYPE_128_BIT_KEY: 16,
}

_STRING_TYPES = (
    DATA_TYPE_OCTET_STRING,
    DATA_TYPE_CHAR_STRING,
    DATA_TYPE_LONG_OCTET_STRING,
    DATA_TYPE_LONG_CHAR_STRING,
)


def cluster_name(cluster_id):
    """Return human-readable name for a cluster id."""
    return _CLUSTER_NAMES.get(int(cluster_id), "unknown")


def data_type_name(data_type):
    """Return human-readable name for a ZCL data type id."""
    return _DATA_TYPE_NAMES.get(int(data_type), "unknown")


def data_type_size(data_type):
    """Return size for fixed-size types, or None for variable-size types."""
    return _FIXED_DATA_TYPE_SIZES.get(int(data_type))


def is_string_type(data_type):
    """Return True if data type is one of ZCL string types."""
    return int(data_type) in _STRING_TYPES
